### PR TITLE
Ace jester90/command processor update

### PR DESCRIPTION
**Pull request by AceJester90**

### CODE REVIEW

**Comment by AceJester90** [comment]
Sorry for a bit of a mess, couldn't push remotely from git in WSL for some reason so had to manually upload and change them here.

**Comment by conormckenzie** [comment]
@AceJester90 Git can be tricky to learn the ins and outs of so I understand. Creating a new branch off of the new dev branch is usually not the most efficient solution, but it is a solution.

In this case, since the last PR to dev changed many files in small ways (wherever there was console output), trying to rebase your work-in-progress branch off of dev could be complicated.

In general though, rebasing off of the newly updated branch is what I've found to be a pretty good way to resolve it most of the time.
Sometimes I'll do resolve the merge conflict by making a merge commit, which is maybe simpler to understand. Git has a tutorial on this:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

And many LLM assistants can help through the process if you get stuck.

**Comment by conormckenzie** [comment]
> Sorry for a bit of a mess, couldn't push remotely from git in WSL for some reason so had to manually upload and change them here.

As for this, I have struggled with WSL as well so I understand. I've found more success developing on bare Linux or through a Linux virtual machine, though bare Linux is not always feasible, as is a Linux virtual machine.

Hopefully you are able to resolve it, as manually changing the files through GitHub won't always be feasible either as the project gets bigger.

**Comment by AceJester90** [comment]
I see, thanks for info. I'll look into it.

**Review by conormckenzie — APPROVED** [review]

**Pull request merged**
